MVCProKampi/Controllers/WriterController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntitiyFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProKampi.Controllers
{
	public class WriterController : Controller
	{
		WriterManager wm = new WriterManager(new EFWriterDal());
		public ActionResult writerList()
		{
			var values = wm.GetWriterList();
			return View(values);
		}
		[HttpGet]
		public ActionResult writerAdd()
		{
			return View();
		}
		[HttpPost]
		public ActionResult writerAdd(Writer writer)
		{
			WriterValidator vd= new WriterValidator();
			ValidationResult result= vd.Validate(writer);
			if (result.IsValid)
			{
				wm.WriterAdd(writer);
				return RedirectToAction("writerList");
			}
			else
			{
				foreach (var item in result.Errors)
				{
					ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
				}
			}
			return View();
		}
		[HttpGet]
		public ActionResult writerUpdate(int id)
		{
			var value = wm.GetWriter(id);
			return View(value);
		}
		[HttpPost]
		public ActionResult writerUpdate(Writer writer)
		{
			wm.WriterUpdate(writer);
			return RedirectToAction("writerList");
		}
	}
}

MVCProKampi/Views/Writer/writerAdd.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "writerAdd";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}
<br />
<div class="container">
    <h2 class="offcanvas-header" style="margin-left:350px;">Yeni Yazar Ekleme Sayfası</h2>
</div>
<br />
<div class="container">
    @using (Html.BeginForm("writerAdd", "Writer", FormMethod.Post))
    {
        <div>
            @Html.Label("Yazar Adı:")
            @Html.TextBoxFor(x => x.writerName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.writerName, "", new { @class = "text-danger" })
            <br />
            @Html.Label("Yazar Soyadı:")
            @Html.TextBoxFor(x => x.writerSurname, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.writerSurname, "", new { @class = "text-danger" })
            <br />
            @Html.Label("Yazar  Tittle:")
            @Html.TextBoxFor(x => x.writerTittle, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.writerTittle, "", new { @class = "text-danger" })
            <br />
            @Html.Label("Yazar Konuları:")
            @Html.TextBoxFor(x => x.writerAbout, new { @class = "form-control" })
            <br />
            @Html.Label("Yazar Mail:")
            @Html.TextBoxFor(x => x.writerMail, new { @class = "form-control" })
            <br />
            @Html.Label("Yazar Şifre:")
            @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
            <br />
            @Html.Label("Yazar Resim Yolu:")
            @Html.TextBoxFor(x => x.writerImage, new { @class = "form-control" })
            <br />
            <button class="btn btn-outline-dark">Kaydet</button>
        </div>
    }
</div>

MVCProKampi/Views/Writer/writerList.cshtml
@model List<EntityLayer.Concrete.Writer>
@{
    ViewBag.Title = "writerList";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- /.navbar -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Yazarlar Sayfası</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card card-solid">
            <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch">
                    @foreach (var item in Model)
                    {
                        <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                            <div class="card bg-light">
                                <div class="card-header text-muted border-bottom-0">
                                   @item.writerTittle
                                </div>
                                <div class="card-body pt-0">
                                    <div class="row">
                                        <div class="col-7">
                                            <h2 class="lead"><b>@item.writerName @item.writerSurname</b></h2>
                                            <p class="text-muted text-sm"><b> </b> @item.writerAbout </p>
                                            <ul class="ml-4 mb-0 fa-ul text-muted">
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> @item.writerMail</li>
                                               
                                            </ul>
                                        </div>
                                        <div class="col-5 text-center">
                                            <img src="@item.writerImage" alt="" class="img-circle img-fluid">
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <div class="text-right">
                                        <a href="/Heading/headingListWriter/@item.writerID" class="btn btn-sm bg-teal">
                                            <i class="fas fa-comments">Başlıklar</i>
                                        </a>
                                        <a href="/Writer/writerUpdate/@item.writerID" class="btn btn-sm btn-primary">
                                            <i class="fas fa-user"></i> Düzenle
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
</body>
</html>

MVCProKampi/Views/Writer/writerUpdate.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "writerUpdate";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}
<br />
<div class="container">
    <h2 class="offcanvas-header" style="margin-left:350px;">Yazar Bilgi Güncelleme Sayfası</h2>
</div>
<div class="container">
    @using (Html.BeginForm("writerUpdate", "Writer", FormMethod.Post))
    {
        <div>
            @Html.HiddenFor(x=>x.writerID)
            @Html.Label("Yazar Adı:")
            @Html.TextBoxFor(x => x.writerName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.writerName, "", new { @class = "text-danger" })
            <br />
            @Html.Label("Yazar Soyadı:")
            @Html.TextBoxFor(x => x.writerSurname, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.writerSurname, "", new { @class = "text-danger" })
            <br />
            @Html.Label("Yazar  Tittle:")
            @Html.TextBoxFor(x => x.writerTittle, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.writerTittle, "", new { @class = "text-danger" })
            <br />
            @Html.Label("Yazar Konuları:")
            @Html.TextBoxFor(x => x.writerAbout, new { @class = "form-control" })
            <br />
            @Html.Label("Yazar Mail:")
            @Html.TextBoxFor(x => x.writerMail, new { @class = "form-control" })
            <br />
            @Html.Label("Yazar Şifre:")
            @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
            <br />
            @Html.Label("Yazar Resim Yolu:")
            @Html.TextBoxFor(x => x.writerImage, new { @class = "form-control" })
            <br />
            <button class="btn btn-outline-dark">Kaydet</button>
        </div>
    }
</div>