MVCProKampi/Controllers/HeadingController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntitiyFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProKampi.Controllers
{
	public class HeadingController : Controller
	{
		HeadingManager hm = new HeadingManager(new EFHeadingDal());
		CategoryManager cm = new CategoryManager(new EFCategoryDal());
		WriterManager wm = new WriterManager(new EFWriterDal());
		public ActionResult headingList()
		{
			var values = hm.GetHeaadingList();
			return View(values);
		}

        public ActionResult headingReport()
        {
            var values = hm.GetHeaadingList();
            return View(values);
        }

        Context c = new Context();
        public ActionResult headingListWriter(int id)
        {
            var values = c.Headings.Where(x=>x.writerID == id).ToList();
            return View(values);
        }
        [HttpGet]
		public ActionResult headingAdd()
		{
			List<SelectListItem> cate = (from x in cm.GetCategoriesList()
										 select new SelectListItem
										 {
											 Text = x.categoryName,
											 Value = x.categoryID.ToString()
										 }).ToList();
			ViewBag.clist = cate;


			List<SelectListItem> wrt = (from x in wm.GetWriterList()
										select new SelectListItem
										{
											Text = x.writerName + " " + x.writerSurname,
											Value = x.writerID.ToString()
										}).ToList();
			ViewBag.wlist = wrt;
			return View();
		}
		[HttpPost]
		public ActionResult headingAdd(Heading heading)
		{
			heading.headindDate = DateTime.Parse(DateTime.Now.ToShortDateString());
			hm.HeadingAdd(heading);
			return RedirectToAction("headingList");
		}
		[HttpGet]
		public ActionResult headingUpdate(int id)
		{
			List<SelectListItem> cate = (from x in cm.GetCategoriesList()
										 select new SelectListItem
										 {
											 Text = x.categoryName,
											 Value = x.categoryID.ToString()
										 }).ToList();
			ViewBag.clist = cate;

			var values = hm.GetHeading(id);
			return View(values);
		}
		[HttpPost]
		public ActionResult headingUpdate(Heading heading)
		{

			hm.HeadingUpdate(heading);
			return RedirectToAction("headingList");
		}
		public ActionResult headingDelete(int id)
		{
			var values=hm.GetHeading(id);
			values.headingStatus = false;
			hm.HeadingRemove(values);
			return RedirectToAction("headingList");
		}
	}
}

MVCProKampi/Views/Heading/headingAdd.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "headingAdd";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<br />
<div class="container">
    <h2 class="offcanvas-header" style="margin-left:350px;">Yeni Başlık Ekleme Sayfası</h2>
</div>
<br />
<div class="container">
    @using (Html.BeginForm("headingAdd", "Heading", FormMethod.Post))
    {
        <div>
            @Html.Label("Başlık Adı:")
            @Html.TextBoxFor(x => x.headingName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.headingName, "", new { @class = "text-danger" })
            <br />
            @Html.Label("Kategorisi:")
            @Html.DropDownListFor(x => x.categoryID, (List<SelectListItem>)ViewBag.clist, new { @class = "form-control" })
            <br />
            @ViewBag.wm
            @*@Html.Label("Yazarı:")
            @Html.DropDownListFor(x => x.writerID, (List<SelectListItem>)ViewBag.wlist, new { @class = "form-control" })*@
            <br />

            <button class="btn btn-outline-dark">Kaydet</button>
        </div>
    }
</div>

MVCProKampi/Views/Heading/headingList.cshtml
@model List<EntityLayer.Concrete.Heading>
@{
    ViewBag.Title = "headingList";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}
@{string color = "";
    string name = "";
    string headingColor = "";}
<br />
<div class="container">
    <h2 class="content-header">Başlıklar Listesi</h2>
</div>
<br />
<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Tablo</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 15%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 10%">
                                Durum
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.category.categoryName == "Spor")
                            {
                                color = "badge badge-success";
                            }
                            if (item.category.categoryName == "Tiyatro")
                            {
                                color = "badge badge-warning";
                            }

                            if (item.category.categoryName == "Moda")
                            {
                                color = "badge badge-danger";
                            }

                            if (item.category.categoryName == "Teknoloji")
                            {
                                color = "badge badge-info";
                            }
                            if (item.category.categoryName == "Eğitim")
                            {
                                color = "badge badge-secondary";
                            }
                            if (item.headingStatus == true)
                            {
                                headingColor = "badge badge-primary";
                                name = "AKTİF";
                            }
                            if (item.headingStatus == false)
                            {
                                headingColor = "badge badge-dark";
                                name = "PASİF";
                            }

                            <tr>
                                <td>
                                    @item.headingID
                                </td>
                                <td>
                                    <a>
                                        @item.headingName
                                    </a>
                                    <br />
                                    <small>
                                        @item.headindDate.ToShortDateString()
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.writer.writerImage">
                                        </li>
                                    </ul>
                                </td>
                                <td>
                                    @*@item.headingStatus*@ <span class="@headingColor"> @name</span>
                                </td>
                                <td class="project-state">
                                    <span class="@color">@item.category.categoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/contentbyHeading/@item.headingID">
                                        <i class="fas fa-folder">
                                        </i>
                                        Entryler
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/Heading/headingUpdate/@item.headingID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/Heading/headingDelete/@item.headingID">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
</html>
<a class="btn btn-outline-dark" href="/Heading/headingAdd/">Yeni Başlık Ekle</a>

MVCProKampi/Views/Heading/headingListWriter.cshtml
@model List<EntityLayer.Concrete.Heading>
@{
    ViewBag.Title = "headingListWriter";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

@{string color = "";
    string name = "";
    string headingColor = "";}
<br />
<div class="container">
    <h2 class="content-header">Yazara Ait Başlıklar </h2>
</div>
<br />
<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Tablo</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 15%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 10%">
                                Durum
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.category.categoryName == "Spor")
                            {
                                color = "badge badge-success";
                            }
                            if (item.category.categoryName == "Tiyatro")
                            {
                                color = "badge badge-warning";
                            }

                            if (item.category.categoryName == "Moda")
                            {
                                color = "badge badge-danger";
                            }

                            if (item.category.categoryName == "Teknoloji")
                            {
                                color = "badge badge-info";
                            }
                            if (item.category.categoryName == "Eğitim")
                            {
                                color = "badge badge-secondary";
                            }
                            if (item.headingStatus == true)
                            {
                                headingColor = "badge badge-primary";
                                name = "AKTİF";
                            }
                            if (item.headingStatus == false)
                            {
                                headingColor = "badge badge-dark";
                                name = "PASİF";
                            }

                            <tr>
                                <td>
                                    @item.headingID
                                </td>
                                <td>
                                    <a>
                                        @item.headingName
                                    </a>
                                    <br />
                                    <small>
                                        @item.headindDate.ToShortDateString()
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.writer.writerImage">
                                        </li>
                                    </ul>
                                </td>
                                <td>
                                    @*@item.headingStatus*@ <span class="@headingColor"> @name</span>
                                </td>
                                <td class="project-state">
                                    <span class="@color">@item.category.categoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/contentbyHeading/@item.headingID">
                                        <i class="fas fa-folder">
                                        </i>
                                        Entryler
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/Heading/headingUpdate/@item.headingID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/Heading/headingDelete/@item.headingID">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
</html>

MVCProKampi/Views/Heading/headingReport.cshtml
@model List<EntityLayer.Concrete.Heading>
@{
    ViewBag.Title = "headingReport";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<br />
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Raporlama</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
</head>
<body>
    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Adı</th>
                <th>Tarihi</th>
                <th>Yazarı</th>
                <th>Kategorisi</th>
                <th>Durumu</th>
                
            </tr>
        </thead>
        <tbody>
            @foreach (var x in Model)
            {
                <tr>
                    <td>@x.headingID</td>
                    <td>@x.headingName</td>
                    <td>@x.headindDate.ToShortDateString()</td>
                    <td>@x.writer.writerName @x.writer.writerSurname</td>
                    <td>@x.category.categoryName</td>
                    <td>@x.headingStatus</td>
                    
                </tr>
            }

        </tbody>
    </table>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>
    <script>
	$(document).ready(function() {
	    var table = $('#example').DataTable( {
	        lengthChange: false,
	        buttons: [ 'copy', 'excel', 'csv', 'pdf', 'colvis' ]
	    } );

	    table.buttons().container()
	        .appendTo( '#example_wrapper .col-md-6:eq(0)' );
	} );
    </script>
</body>

MVCProKampi/Views/Heading/headingUpdate.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "headingUpdate";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="container">
    <h2 class="offcanvas-header" style="margin-left:350px;">Başlık Güncelleme Sayfası</h2>
</div>
<br />
<div class="container">
    @using (Html.BeginForm("headingUpdate", "Heading", FormMethod.Post))
    {
        <div>
            @Html.HiddenFor(x => x.headingID)
            @Html.Label("Başlık Adı:")
            @Html.TextBoxFor(x => x.headingName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.headingName, "", new { @class = "text-danger" })
            <br />
            @Html.Label("Kategori:")
            @Html.DropDownListFor(x => x.categoryID, (List<SelectListItem>)ViewBag.clist, new { @class = "form-control" })
            <br />
            @Html.Label("Tarih:")
            @Html.TextBoxFor(x => x.headindDate, new { @class = "form-control" })
            <br />
            @Html.Label("Yazar:")
            @Html.TextBoxFor(x => x.writerID, new { @class = "form-control" })

            <br /><br />
            <button class="btn btn-outline-dark">Kaydet</button>
        </div>
    }
</div>